def get_all_sets():
    all_sets = [[('p15a', '15th Anniversary Cards'), ('phtr', '2016 Heroes of the Realm'), ('ph17', '2017 Heroes of the Realm'),
        ('ph18', '2018 Heroes of the Realm'), ('ph19', '2019 Heroes of the Realm'), ('ph20', '2020 Heroes of the Realm'),
        ('ph21', '2021 Heroes of the Realm'), ('p30h', '30th Anniversary History Promos'), ('p30a', '30th Anniversary Play Promos'),
        ('t30a', '30th Anniversary Tokens')], [('afr', 'Adventures in the Forgotten Realms'), ('aafr', 'Adventures in the Forgotten Realms Art Series'),
        ('tafr', 'Adventures in the Forgotten Realms Tokens'), ('aer', 'Aether Revolt'), ('paer', 'Aether Revolt Promos'),
        ('taer', 'Aether Revolt Tokens'), ('arb', 'Alara Reborn'), ('parb', 'Alara Reborn Promos'),
        ('tarb', 'Alara Reborn Tokens'), ('hbg', "Alchemy Horizons: Baldur's Gate"), ('ydmu', 'Alchemy: Dominaria'),
        ('ymid', 'Alchemy: Innistrad'), ('yneo', 'Alchemy: Kamigawa'), ('ysnc', 'Alchemy: New Capenna'),
        ('yone', 'Alchemy: Phyrexia'), ('ybro', "Alchemy: The Brothers' War"), ('all', 'Alliances'),
        ('akh', 'Amonkhet'), ('mp2', 'Amonkhet Invocations'), ('pakh', 'Amonkhet Promos'),
        ('akr', 'Amonkhet Remastered'), ('takh', 'Amonkhet Tokens'), ('ath', 'Anthologies'),
        ('atq', 'Antiquities'), ('apc', 'Apocalypse'), ('papc', 'Apocalypse Promos'),
        ('arn', 'Arabian Nights'), ('arc', 'Archenemy'), ('oarc', 'Archenemy Schemes'),
        ('e01', 'Archenemy: Nicol Bolas'), ('oe01', 'Archenemy: Nicol Bolas Schemes'), ('te01', 'Archenemy: Nicol Bolas Tokens'),
        ('anb', 'Arena Beginner Set'), ('parl', 'Arena League 1996'), ('pal99', 'Arena League 1999'),
        ('pal03', 'Arena League 2003'), ('pal04', 'Arena League 2004'), ('pal05', 'Arena League 2005'),
        ('pal06', 'Arena League 2006'), ('oana', 'Arena New Player Experience Cards'), ('xana', 'Arena New Player Experience Extras'),
        ('palp', 'Asia Pacific Land Program'), ('past', 'Astral Cards'), ('avr', 'Avacyn Restored'),
        ('pavr', 'Avacyn Restored Promos'), ('tavr', 'Avacyn Restored Tokens')], [('brb', 'Battle Royale Box Set'),
        ('aclb', "Battle for Baldur's Gate Art Series"), ('tclb', "Battle for Baldur's Gate Tokens"), ('bfz', 'Battle for Zendikar'),
        ('pbfz', 'Battle for Zendikar Promos'), ('tbfz', 'Battle for Zendikar Tokens'), ('tbth', 'Battle the Horde'),
        ('bbd', 'Battlebond'), ('tbbd', 'Battlebond Tokens'), ('btd', 'Beatdown Box Set'),
        ('bok', 'Betrayers of Kamigawa'), ('pbok', 'Betrayers of Kamigawa Promos'), ('bng', 'Born of the Gods'),
        ('thp2', "Born of the Gods Hero's Path"), ('pbng', 'Born of the Gods Promos'), ('tbng', 'Born of the Gods Tokens')],
        [('pcel', 'Celebration Cards'), ('q07', 'Challenger Decks 2022'), ('chk', 'Champions of Kamigawa'),
        ('pchk', 'Champions of Kamigawa Promos'), ('pcmp', 'Champs and States'), ('chr', 'Chronicles'),
        ('6ed', 'Classic Sixth Edition'), ('csp', 'Coldsnap'), ('pcsp', 'Coldsnap Promos'),
        ('cst', 'Coldsnap Theme Decks'), ('ced', 'Collectors’ Edition'), ('cmd', 'Commander 2011'),
        ('c13', 'Commander 2013'), ('c14', 'Commander 2014'), ('tc14', 'Commander 2014 Tokens'),
        ('c15', 'Commander 2015'), ('tc15', 'Commander 2015 Tokens'), ('c16', 'Commander 2016'),
        ('tc16', 'Commander 2016 Tokens'), ('c17', 'Commander 2017'), ('tc17', 'Commander 2017 Tokens'),
        ('c18', 'Commander 2018'), ('tc18', 'Commander 2018 Tokens'), ('c19', 'Commander 2019'),
        ('tc19', 'Commander 2019 Tokens'), ('c20', 'Commander 2020'), ('tc20', 'Commander 2020 Tokens'),
        ('c21', 'Commander 2021'), ('tc21', 'Commander 2021 Tokens'), ('cma', 'Commander Anthology'),
        ('tcma', 'Commander Anthology Tokens'), ('tcm2', 'Commander Anthology Volume II Tokens'), ('cc2', 'Commander Collection: Black'),
        ('cc1', 'Commander Collection: Green'), ('cmr', 'Commander Legends'), ('tcmr', 'Commander Legends Tokens'),
        ('clb', "Commander Legends: Battle for Baldur's Gate"), ('cmm', 'Commander Masters'), ('cm1', "Commander's Arsenal"),
        ('con', 'Conflux'), ('pcon', 'Conflux Promos'), ('tcon', 'Conflux Tokens'),
        ('cns', 'Conspiracy'), ('pcns', 'Conspiracy Promos'), ('tcns', 'Conspiracy Tokens'),
        ('cn2', 'Conspiracy: Take the Crown'), ('tcn2', 'Conspiracy: Take the Crown Tokens'), ('m19', 'Core Set 2019'),
        ('pm19', 'Core Set 2019 Promos'), ('tm19', 'Core Set 2019 Tokens'), ('m20', 'Core Set 2020'),
        ('pm20', 'Core Set 2020 Promos'), ('tm20', 'Core Set 2020 Tokens'), ('m21', 'Core Set 2021'),
        ('tm21', 'Core Set 2021 Tokens'), ('avow', 'Crimson Vow Art Series'), ('voc', 'Crimson Vow Commander'),
        ('tvoc', 'Crimson Vow Commander Tokens')], [('plgm', 'DCI Legend Membership'), ('pdci', 'DCI Promos'),
        ('dka', 'Dark Ascension'), ('pdka', 'Dark Ascension Promos'), ('tdka', 'Dark Ascension Tokens'),
        ('dst', 'Darksteel'), ('pdst', 'Darksteel Promos'), ('dkm', 'Deckmasters'),
        ('tdag', 'Defeat a God'), ('dis', 'Dissension'), ('pdis', 'Dissension Promos'),
        ('dom', 'Dominaria'), ('pdom', 'Dominaria Promos'), ('dmr', 'Dominaria Remastered'),
        ('tdmr', 'Dominaria Remastered Tokens'), ('tdom', 'Dominaria Tokens'), ('dmu', 'Dominaria United'),
        ('admu', 'Dominaria United Art Series'), ('dmc', 'Dominaria United Commander'), ('tdmc', 'Dominaria United Commander Tokens'),
        ('wdmu', 'Dominaria United Japanese Promo Tokens'), ('tdmu', 'Dominaria United Tokens'), ('2xm', 'Double Masters'),
        ('2x2', 'Double Masters 2022'), ('t2x2', 'Double Masters 2022 Tokens'), ('t2xm', 'Double Masters Tokens'),
        ('pdrc', 'Dragon Con'), ('dgm', "Dragon's Maze"), ('pdgm', "Dragon's Maze Promos"),
        ('tdgm', "Dragon's Maze Tokens"), ('dtk', 'Dragons of Tarkir'), ('pdtk', 'Dragons of Tarkir Promos'),
        ('tdtk', 'Dragons of Tarkir Tokens'), ('dvd', 'Duel Decks Anthology: Divine vs. Demonic'), ('evg', 'Duel Decks Anthology: Elves vs. Goblins'),
        ('tevg', 'Duel Decks Anthology: Elves vs. Goblins Tokens'), ('jvc', 'Duel Decks Anthology: Jace vs. Chandra'), ('ddh', 'Duel Decks: Ajani vs. Nicol Bolas'),
        ('tddh', 'Duel Decks: Ajani vs. Nicol Bolas Tokens'), ('ddq', 'Duel Decks: Blessed vs. Cursed'), ('ddc', 'Duel Decks: Divine vs. Demonic'),
        ('tddc', 'Duel Decks: Divine vs. Demonic Tokens'), ('ddo', 'Duel Decks: Elspeth vs. Kiora'), ('ddf', 'Duel Decks: Elspeth vs. Tezzeret'),
        ('dd1', 'Duel Decks: Elves vs. Goblins'), ('ddu', 'Duel Decks: Elves vs. Inventors'), ('ddd', 'Duel Decks: Garruk vs. Liliana'),
        ('ddl', 'Duel Decks: Heroes vs. Monsters'), ('tddl', 'Duel Decks: Heroes vs. Monsters Tokens'), ('ddj', 'Duel Decks: Izzet vs. Golgari'),
        ('dd2', 'Duel Decks: Jace vs. Chandra'), ('ddm', 'Duel Decks: Jace vs. Vraska'), ('ddg', 'Duel Decks: Knights vs. Dragons'),
        ('ddt', 'Duel Decks: Merfolk vs. Goblins'), ('tddt', 'Duel Decks: Merfolk vs. Goblins Tokens'), ('dds', 'Duel Decks: Mind vs. Might'),
        ('td2', 'Duel Decks: Mirrodin Pure vs. New Phyrexia'), ('ddr', 'Duel Decks: Nissa vs. Ob Nixilis'), ('dde', 'Duel Decks: Phyrexia vs. the Coalition'),
        ('tdde', 'Duel Decks: Phyrexia vs. the Coalition Tokens'), ('ddk', 'Duel Decks: Sorin vs. Tibalt'), ('ddn', 'Duel Decks: Speed vs. Cunning'),
        ('ddi', 'Duel Decks: Venser vs. Koth'), ('tddi', 'Duel Decks: Venser vs. Koth Tokens'), ('ddp', 'Duel Decks: Zendikar vs. Eldrazi'),
        ('dpa', 'Duels of the Planeswalkers'), ('pdtp', 'Duels of the Planeswalkers 2009 Promos '), ('pdp10', 'Duels of the Planeswalkers 2010 Promos '),
        ('pdp12', 'Duels of the Planeswalkers 2012 Promos '), ('pdp13', 'Duels of the Planeswalkers 2013 Promos '), ('pdp14', 'Duels of the Planeswalkers 2014 Promos '),
        ('pdp15', 'Duels of the Planeswalkers 2015 Promos ')], [('8ed', 'Eighth Edition'), ('emn', 'Eldritch Moon'),
        ('pemn', 'Eldritch Moon Promos'), ('temn', 'Eldritch Moon Tokens'), ('ema', 'Eternal Masters'),
        ('tema', 'Eternal Masters Tokens'), ('pewk', 'Eternal Weekend 2022'), ('pelp', 'European Land Program'),
        ('eve', 'Eventide'), ('peve', 'Eventide Promos'), ('teve', 'Eventide Tokens'),
        ('exo', 'Exodus'), ('pexo', 'Exodus Promos'), ('e02', 'Explorers of Ixalan')],
        [('tfth', 'Face the Hydra'), ('fem', 'Fallen Empires'), ('frf', 'Fate Reforged'),
        ('cp2', 'Fate Reforged Clash Pack'), ('pfrf', 'Fate Reforged Promos'), ('tfrf', 'Fate Reforged Tokens'),
        ('5dn', 'Fifth Dawn'), ('p5dn', 'Fifth Dawn Promos'), ('5ed', 'Fifth Edition'),
        ('afc', 'Forgotten Realms Commander'), ('tafc', 'Forgotten Realms Commander Tokens'), ('4ed', 'Fourth Edition'),
        ('f03', 'Friday Night Magic 2003'), ('f08', 'Friday Night Magic 2008'), ('f09', 'Friday Night Magic 2009'),
        ('f10', 'Friday Night Magic 2010'), ('f11', 'Friday Night Magic 2011'), ('f12', 'Friday Night Magic 2012'),
        ('f13', 'Friday Night Magic 2013'), ('f14', 'Friday Night Magic 2014'), ('f15', 'Friday Night Magic 2015'),
        ('f16', 'Friday Night Magic 2016'), ('f17', 'Friday Night Magic 2017'), ('f18', 'Friday Night Magic 2018'),
        ('v15', 'From the Vault: Angels'), ('v14', 'From the Vault: Annihilation'), ('drb', 'From the Vault: Dragons'),
        ('v09', 'From the Vault: Exiled'), ('v11', 'From the Vault: Legends'), ('v16', 'From the Vault: Lore'),
        ('v12', 'From the Vault: Realms'), ('v10', 'From the Vault: Relics'), ('v17', 'From the Vault: Transform'),
        ('v13', 'From the Vault: Twenty'), ('fut', 'Future Sight'), ('pfut', 'Future Sight Promos')],
        [('gk1', 'GRN Guild Kit'), ('tgk1', 'GRN Guild Kit Tokens'), ('prwk', 'GRN Ravnica Weekend'),
        ('gdy', 'Game Day Promos'), ('gnt', 'Game Night'), ('gn2', 'Game Night 2019'),
        ('tgn2', 'Game Night 2019 Tokens'), ('gn3', 'Game Night: Free-for-All'), ('gtc', 'Gatecrash'),
        ('pgtc', 'Gatecrash Promos'), ('tgtc', 'Gatecrash Tokens'), ('gs1', 'Global Series Jiang Yanggu & Mu Yanling'),
        ('pgpx', 'Grand Prix Promos'), ('gpt', 'Guildpact'), ('pgpt', 'Guildpact Promos'),
        ('grn', 'Guilds of Ravnica'), ('pgrn', 'Guilds of Ravnica Promos'), ('tgrn', 'Guilds of Ravnica Tokens'),
        ('pgru', 'Guru')], [('phuk', 'Hachette UK'), ('hho', 'Happy Holidays'),
        ('phpr', 'HarperPrism Book Promos'), ('h17', 'HasCon 2017'), ('hml', 'Homelands'),
        ('hou', 'Hour of Devastation'), ('phou', 'Hour of Devastation Promos'), ('thou', 'Hour of Devastation Tokens')],
        [('pidw', 'IDW Comics Inserts'), ('ice', 'Ice Age'), ('ima', 'Iconic Masters'),
        ('iko', 'Ikoria: Lair of Behemoths'), ('tiko', 'Ikoria: Lair of Behemoths Tokens'), ('isd', 'Innistrad'),
        ('pisd', 'Innistrad Promos'), ('tisd', 'Innistrad Tokens'), ('vow', 'Innistrad: Crimson Vow'),
        ('svow', 'Innistrad: Crimson Vow Substitute Cards'), ('tvow', 'Innistrad: Crimson Vow Tokens'), ('dbl', 'Innistrad: Double Feature'),
        ('mid', 'Innistrad: Midnight Hunt'), ('smid', 'Innistrad: Midnight Hunt Substitute Cards'), ('tmid', 'Innistrad: Midnight Hunt Tokens'),
        ('cei', 'Intl. Collectors’ Edition'), ('itp', 'Introductory Two-Player Set'), ('inv', 'Invasion'),
        ('xln', 'Ixalan'), ('pxln', 'Ixalan Promos'), ('txln', 'Ixalan Tokens')],
        [('jou', 'Journey into Nyx'), ('thp3', "Journey into Nyx Hero's Path"), ('pjou', 'Journey into Nyx Promos'),
        ('tjou', 'Journey into Nyx Tokens'), ('jgp', 'Judge Gift Cards 1998'), ('g04', 'Judge Gift Cards 2004'),
        ('g06', 'Judge Gift Cards 2006'), ('g07', 'Judge Gift Cards 2007'), ('g08', 'Judge Gift Cards 2008'),
        ('g09', 'Judge Gift Cards 2009'), ('g10', 'Judge Gift Cards 2010'), ('g11', 'Judge Gift Cards 2011'),
        ('j12', 'Judge Gift Cards 2012'), ('j13', 'Judge Gift Cards 2013'), ('j14', 'Judge Gift Cards 2014'),
        ('j15', 'Judge Gift Cards 2015'), ('j16', 'Judge Gift Cards 2016'), ('j17', 'Judge Gift Cards 2017'),
        ('j18', 'Judge Gift Cards 2018'), ('j19', 'Judge Gift Cards 2019'), ('j20', 'Judge Gift Cards 2020'),
        ('pj21', 'Judge Gift Cards 2021'), ('p22', 'Judge Gift Cards 2022'), ('p23', 'Judge Gift Cards 2023'),
        ('jud', 'Judgment'), ('pjud', 'Judgment Promos'), ('jmp', 'Jumpstart'),
        ('j22', 'Jumpstart 2022'), ('fj22', 'Jumpstart 2022 Front Cards'), ('fjmp', 'Jumpstart Front Cards'),
        ('j21', 'Jumpstart: Historic Horizons'), ('psus', 'Junior Super Series')], [('kld', 'Kaladesh'),
        ('mps', 'Kaladesh Inventions'), ('pkld', 'Kaladesh Promos'), ('klr', 'Kaladesh Remastered'),
        ('tkld', 'Kaladesh Tokens'), ('khm', 'Kaldheim'), ('akhm', 'Kaldheim Art Series'),
        ('khc', 'Kaldheim Commander'), ('tkhc', 'Kaldheim Commander Tokens'), ('skhm', 'Kaldheim Substitute Cards'),
        ('tkhm', 'Kaldheim Tokens'), ('neo', 'Kamigawa: Neon Dynasty'), ('sneo', 'Kamigawa: Neon Dynasty Substitute Cards'),
        ('tneo', 'Kamigawa: Neon Dynasty Tokens'), ('ktk', 'Khans of Tarkir'), ('pktk', 'Khans of Tarkir Promos'),
        ('tktk', 'Khans of Tarkir Tokens')], [('l12', 'League Tokens 2012'), ('l13', 'League Tokens 2013'),
        ('l14', 'League Tokens 2014'), ('l15', 'League Tokens 2015'), ('l16', 'League Tokens 2016'),
        ('l17', 'League Tokens 2017'), ('olgc', 'Legacy Championship'), ('pz1', 'Legendary Cube Prize Pack'),
        ('leg', 'Legends'), ('lgn', 'Legions'), ('plgn', 'Legions Promos'),
        ('lea', 'Limited Edition Alpha'), ('leb', 'Limited Edition Beta'), ('lrw', 'Lorwyn'),
        ('plrw', 'Lorwyn Promos'), ('tlrw', 'Lorwyn Tokens'), ('plg20', 'Love Your LGS 2020'),
        ('plg21', 'Love Your LGS 2021'), ('plg22', 'Love Your LGS 2022'), ('plny', 'Lunar New Year 2018 ')],
        [('ppc1', 'M15 Prerelease Challenge'), ('g18', 'M19 Gift Pack'), ('pss3', 'M19 Standard Showdown'),
        ('ppp1', 'M20 Promo Packs'), ('m10', 'Magic 2010'), ('pm10', 'Magic 2010 Promos'),
        ('tm10', 'Magic 2010 Tokens'), ('m11', 'Magic 2011'), ('pm11', 'Magic 2011 Promos'),
        ('tm11', 'Magic 2011 Tokens'), ('m12', 'Magic 2012'), ('pm12', 'Magic 2012 Promos'),
        ('tm12', 'Magic 2012 Tokens'), ('m13', 'Magic 2013'), ('pm13', 'Magic 2013 Promos'),
        ('tm13', 'Magic 2013 Tokens'), ('m14', 'Magic 2014'), ('pm14', 'Magic 2014 Promos'),
        ('tm14', 'Magic 2014 Tokens'), ('m15', 'Magic 2015'), ('cp1', 'Magic 2015 Clash Pack'),
        ('pm15', 'Magic 2015 Promos'), ('tm15', 'Magic 2015 Tokens'), ('pmoa', 'Magic Online Avatars'),
        ('prm', 'Magic Online Promos'), ('td0', 'Magic Online Theme Decks'), ('ori', 'Magic Origins'),
        ('cp3', 'Magic Origins Clash Pack'), ('pori', 'Magic Origins Promos'), ('tori', 'Magic Origins Tokens'),
        ('mpr', 'Magic Player Rewards 2001'), ('pr2', 'Magic Player Rewards 2002'), ('p03', 'Magic Player Rewards 2003'),
        ('p04', 'Magic Player Rewards 2004'), ('p05', 'Magic Player Rewards 2005'), ('p06', 'Magic Player Rewards 2006'),
        ('p07', 'Magic Player Rewards 2007'), ('p08', 'Magic Player Rewards 2008'), ('p09', 'Magic Player Rewards 2009'),
        ('p10', 'Magic Player Rewards 2010'), ('p11', 'Magic Player Rewards 2011'), ('pmps06', 'Magic Premiere Shop 2006'),
        ('pmps08', 'Magic Premiere Shop 2008'), ('pmps09', 'Magic Premiere Shop 2009'), ('pmps10', 'Magic Premiere Shop 2010'),
        ('pmps11', 'Magic Premiere Shop 2011'), ('pf19', 'MagicFest 2019'), ('pf20', 'MagicFest 2020'),
        ('mom', 'March of the Machine'), ('moc', 'March of the Machine Commander'), ('tmom', 'March of the Machine Tokens'),
        ('mat', 'March of the Machine: The Aftermath'), ('a25', 'Masters 25'), ('ta25', 'Masters 25 Tokens'),
        ('me1', 'Masters Edition'), ('me2', 'Masters Edition II'), ('me3', 'Masters Edition III'),
        ('me4', 'Masters Edition IV'), ('pmei', 'Media Inserts'), ('mmq', 'Mercadian Masques'),
        ('pmmq', 'Mercadian Masques Promos'), ('amid', 'Midnight Hunt Art Series'), ('mic', 'Midnight Hunt Commander'),
        ('mir', 'Mirage'), ('mrd', 'Mirrodin'), ('mbs', 'Mirrodin Besieged'),
        ('pmbs', 'Mirrodin Besieged Promos'), ('tmbs', 'Mirrodin Besieged Tokens'), ('pmrd', 'Mirrodin Promos'),
        ('pbook', 'Miscellaneous Book Promos'), ('mh1', 'Modern Horizons'), ('mh2', 'Modern Horizons 2'),
        ('amh2', 'Modern Horizons 2 Art Series'), ('tmh2', 'Modern Horizons 2 Tokens'), ('amh1', 'Modern Horizons Art Series'),
        ('pmh1', 'Modern Horizons Promos'), ('tmh1', 'Modern Horizons Tokens'), ('mma', 'Modern Masters'),
        ('mm2', 'Modern Masters 2015'), ('tmm2', 'Modern Masters 2015 Tokens'), ('mm3', 'Modern Masters 2017'),
        ('tmm3', 'Modern Masters 2017 Tokens'), ('tmma', 'Modern Masters Tokens'), ('mor', 'Morningtide'),
        ('pmor', 'Morningtide Promos'), ('tmor', 'Morningtide Tokens'), ('mgb', 'Multiverse Gift Box'),
        ('mul', 'Multiverse Legends'), ('cmb1', 'Mystery Booster Playtest Cards 2019'), ('cmb2', 'Mystery Booster Playtest Cards 2021'),
        ('med', 'Mythic Edition'), ('tmed', 'Mythic Edition Tokens')], [('pnat', 'Nationals Promos'),
        ('nem', 'Nemesis'), ('aneo', 'Neon Dynasty Art Series'), ('nec', 'Neon Dynasty Commander'),
        ('tnec', 'Neon Dynasty Commander Tokens'), ('asnc', 'New Capenna Art Series'), ('ncc', 'New Capenna Commander'),
        ('tncc', 'New Capenna Commander Tokens'), ('nph', 'New Phyrexia'), ('pnph', 'New Phyrexia Promos'),
        ('tnph', 'New Phyrexia Tokens'), ('9ed', 'Ninth Edition'), ('p9ed', 'Ninth Edition Promos')],
        [('ogw', 'Oath of the Gatewatch'), ('pogw', 'Oath of the Gatewatch Promos'), ('togw', 'Oath of the Gatewatch Tokens'),
        ('ody', 'Odyssey'), ('pody', 'Odyssey Promos'), ('ons', 'Onslaught'),
        ('pons', 'Onslaught Promos'), ('phel', 'Open the Helvault')], [('one', 'Phyrexia: All Will Be One'),
        ('aone', 'Phyrexia: All Will Be One Art Series'), ('onc', 'Phyrexia: All Will Be One Commander'), ('tonc', 'Phyrexia: All Will Be One Commander Tokens'),
        ('wone', 'Phyrexia: All Will Be One Japanese Promo Tokens'), ('fone', 'Phyrexia: All Will Be One Jumpstart Front Cards'), ('tone', 'Phyrexia: All Will Be One Tokens'),
        ('plc', 'Planar Chaos'), ('pplc', 'Planar Chaos Promos'), ('hop', 'Planechase'),
        ('pc2', 'Planechase 2012'), ('opc2', 'Planechase 2012 Planes'), ('pca', 'Planechase Anthology'),
        ('tpca', 'Planechase Anthology Tokens'), ('ohop', 'Planechase Planes'), ('phop', 'Planechase Promos'),
        ('pls', 'Planeshift'), ('pwcs', 'Planeswalker Championship Promos'), ('ptg', 'Ponies: The Galloping'),
        ('por', 'Portal'), ('p02', 'Portal Second Age'), ('ptk', 'Portal Three Kingdoms'),
        ('pptk', 'Portal: Three Kingdoms Promos'), ('pd2', 'Premium Deck Series: Fire and Lightning'), ('pd3', 'Premium Deck Series: Graveborn'),
        ('h09', 'Premium Deck Series: Slivers'), ('ppro', 'Pro Tour Promos'), ('pcy', 'Prophecy'),
        ('ppcy', 'Prophecy Promos')], [('gk2', 'RNA Guild Kit'), ('tgk2', 'RNA Guild Kit Tokens'),
        ('prw2', 'RNA Ravnica Weekend'), ('rna', 'Ravnica Allegiance'), ('prna', 'Ravnica Allegiance Promos'),
        ('trna', 'Ravnica Allegiance Tokens'), ('rav', 'Ravnica: City of Guilds'), ('prav', 'Ravnica: City of Guilds Promos'),
        ('prcq', 'Regional Championship Qualifiers 2022'), ('pr23', 'Regional Championship Qualifiers 2023'), ('pres', 'Resale Promos'),
        ('rtr', 'Return to Ravnica'), ('prtr', 'Return to Ravnica Promos'), ('trtr', 'Return to Ravnica Tokens'),
        ('3ed', 'Revised Edition'), ('roe', 'Rise of the Eldrazi'), ('proe', 'Rise of the Eldrazi Promos'),
        ('troe', 'Rise of the Eldrazi Tokens'), ('rix', 'Rivals of Ixalan'), ('prix', 'Rivals of Ixalan Promos'),
        ('trix', 'Rivals of Ixalan Tokens')], [('psdc', 'San Diego Comic-Con 2013'), ('ps14', 'San Diego Comic-Con 2014'),
        ('ps15', 'San Diego Comic-Con 2015'), ('ps16', 'San Diego Comic-Con 2016'), ('ps17', 'San Diego Comic-Con 2017'),
        ('ps18', 'San Diego Comic-Con 2018'), ('ps19', 'San Diego Comic-Con 2019'), ('sok', 'Saviors of Kamigawa'),
        ('psok', 'Saviors of Kamigawa Promos'), ('som', 'Scars of Mirrodin'), ('psom', 'Scars of Mirrodin Promos'),
        ('tsom', 'Scars of Mirrodin Tokens'), ('scg', 'Scourge'), ('slc', 'Secret Lair 30th Anniversary Countdown Kit'),
        ('sld', 'Secret Lair Drop'), ('slp', 'Secret Lair Showdown'), ('slu', 'Secret Lair: Ultimate Edition'),
        ('psdg', 'Sega Dreamcast Cards'), ('7ed', 'Seventh Edition'), ('shm', 'Shadowmoor'),
        ('pshm', 'Shadowmoor Promos'), ('tshm', 'Shadowmoor Tokens'), ('sis', 'Shadows of the Past'),
        ('soi', 'Shadows over Innistrad'), ('psoi', 'Shadows over Innistrad Promos'), ('sir', 'Shadows over Innistrad Remastered'),
        ('tsoi', 'Shadows over Innistrad Tokens'), ('ala', 'Shards of Alara'), ('pala', 'Shards of Alara Promos'),
        ('tala', 'Shards of Alara Tokens'), ('ss3', 'Signature Spellbook: Chandra'), ('ss2', 'Signature Spellbook: Gideon'),
        ('ss1', 'Signature Spellbook: Jace'), ('s99', 'Starter 1999'), ('s00', 'Starter 2000'),
        ('tscd', 'Starter Commander Deck Tokens'), ('scd', 'Starter Commander Decks'), ('sch', 'Store Championships'),
        ('snc', 'Streets of New Capenna'), ('ptsnc', 'Streets of New Capenna Southeast Asia Tokens'), ('tsnc', 'Streets of New Capenna Tokens'),
        ('astx', 'Strixhaven Art Series'), ('sta', 'Strixhaven Mystical Archive'), ('stx', 'Strixhaven: School of Mages'),
        ('sstx', 'Strixhaven: School of Mages Substitute Cards'), ('tstx', 'Strixhaven: School of Mages Tokens'), ('sth', 'Stronghold'),
        ('psth', 'Stronghold Promos'), ('sum', 'Summer Magic / Edgar')], [('ltc', 'Tales of Middle-earth Commander'),
        ('ptkdf', 'Tarkir Dragonfury'), ('tmp', 'Tempest'), ('ptmp', 'Tempest Promos'),
        ('tpr', 'Tempest Remastered'), ('10e', 'Tenth Edition'), ('t10e', 'Tenth Edition Tokens'),
        ('bro', "The Brothers' War"), ('abro', "The Brothers' War Art Series"), ('brc', "The Brothers' War Commander"),
        ('tbrc', "The Brothers' War Commander Tokens"), ('pbro', "The Brothers' War Promos"), ('brr', "The Brothers' War Retro Artifacts"),
        ('tbro', "The Brothers' War Tokens"), ('drk', 'The Dark'), ('ltr', 'The Lord of the Rings: Tales of Middle-earth'),
        ('ths', 'Theros'), ('thb', 'Theros Beyond Death'), ('tthb', 'Theros Beyond Death Tokens'),
        ('thp1', "Theros Hero's Path"), ('pths', 'Theros Promos'), ('tths', 'Theros Tokens'),
        ('eld', 'Throne of Eldraine'), ('teld', 'Throne of Eldraine Tokens'), ('tsp', 'Time Spiral'),
        ('ptsp', 'Time Spiral Promos'), ('tsr', 'Time Spiral Remastered'), ('ttsr', 'Time Spiral Remastered Tokens'),
        ('tsb', 'Time Spiral Timeshifted'), ('tor', 'Torment'), ('bot', 'Transformers'),
        ('tbot', 'Transformers Tokens'), ('pz2', 'Treasure Chest')], [('purl', 'URL/Convention Promos'),
        ('ugin', "Ugin's Fate"), ('puma', 'Ultimate Box Topper'), ('uma', 'Ultimate Masters'),
        ('tuma', 'Ultimate Masters Tokens'), ('unf', 'Unfinity'), ('sunf', 'Unfinity Sticker Sheets'),
        ('tunf', 'Unfinity Tokens'), ('ugl', 'Unglued'), ('tugl', 'Unglued Tokens'),
        ('unh', 'Unhinged'), ('punh', 'Unhinged Promos'), ('slx', 'Universes Within'),
        ('und', 'Unsanctioned'), ('tund', 'Unsanctioned Tokens'), ('ust', 'Unstable'),
        ('pust', 'Unstable Promos'), ('tust', 'Unstable Tokens'), ('uds', "Urza's Destiny"),
        ('puds', "Urza's Destiny Promos"), ('ulg', "Urza's Legacy"), ('pulg', "Urza's Legacy Promos"),
        ('usg', "Urza's Saga"), ('pusg', "Urza's Saga Promos")], [('pvan', 'Vanguard Series'),
        ('ovnt', 'Vintage Championship'), ('vma', 'Vintage Masters'), ('vis', 'Visions')],
        [('war', 'War of the Spark'), ('pwar', 'War of the Spark Promos'), ('twar', 'War of the Spark Tokens'),
        ('40k', 'Warhammer 40,000 Commander'), ('t40k', 'Warhammer 40,000 Tokens'), ('wth', 'Weatherlight'),
        ('pw11', 'Wizards Play Network 2011'), ('pw12', 'Wizards Play Network 2012'), ('pw21', 'Wizards Play Network 2021'),
        ('pw22', 'Wizards Play Network 2022'), ('pwor', 'World Championship Promos'), ('wmc', 'World Magic Cup Qualifiers'),
        ('wwk', 'Worldwake'), ('pwwk', 'Worldwake Promos'), ('twwk', 'Worldwake Tokens')],
        [('pxtc', 'XLN Treasure Chest')], [('pl21', 'Year of the Ox 2021'), ('pl23', 'Year of the Rabbit 2023'),
        ('pl22', 'Year of the Tiger 2022')], [('zen', 'Zendikar'), ('exp', 'Zendikar Expeditions'),
        ('pzen', 'Zendikar Promos'), ('znr', 'Zendikar Rising'), ('aznr', 'Zendikar Rising Art Series'),
        ('znc', 'Zendikar Rising Commander'), ('zne', 'Zendikar Rising Expeditions'), ('sznr', 'Zendikar Rising Substitute Cards'),
        ('tznr', 'Zendikar Rising Tokens'), ('tzen', 'Zendikar Tokens')]]
    
    return all_sets
